import csv
import json
import io
from typing import Dict, Any, List
from datetime import date

class ExportEngine:
    """
    Export Engine for AI-POS data structures (Daily Plans, Schedules, Analytics).
    Supports Markdown, CSV, JSON, and simple HTML/PDF string formats.
    """

    @staticmethod
    def export_plan_markdown(plan_data: Dict[str, Any]) -> str:
        """
        Converts a Daily Plan dictionary into a clean Markdown checklist.
        """
        lines = [
            f"# Daily Study Schedule - {plan_data.get('date', date.today().isoformat())}",
            f"**Total Available Study Hours:** {plan_data.get('total_available_hours', 0.0)} hrs",
            f"**Status:** {'Finalized' if plan_data.get('is_finalized') else 'Draft'}",
            "",
            "## Scheduled Study Sessions",
            ""
        ]

        sessions = plan_data.get("study_sessions", [])
        if not sessions:
            lines.append("_No study sessions scheduled for this date._")
        else:
            for s in sessions:
                task = s.get("task", {})
                status_icon = "✅" if task.get("is_completed") or s.get("status") == "completed" else "⏳"
                lines.append(
                    f"- {status_icon} **{s.get('start_time')} - {s.get('end_time')}** | "
                    f"*{task.get('title', 'Study Task')}* "
                    f"({task.get('estimated_minutes', 0)} mins, Priority: {task.get('priority', 'medium')}, Energy: {task.get('energy_level', 'medium')})"
                )

        lines.append("")
        lines.append("---")
        lines.append("*Generated by AI Personal Operating System (AI-POS)*")
        return "\n".join(lines)

    @staticmethod
    def export_plan_csv(plan_data: Dict[str, Any]) -> str:
        """
        Converts a Daily Plan dictionary into CSV format.
        """
        output = io.StringIO()
        writer = csv.writer(output)
        writer.writerow(["Start Time", "End Time", "Task Title", "Minutes", "Priority", "Energy Level", "Completed"])

        sessions = plan_data.get("study_sessions", [])
        for s in sessions:
            task = s.get("task", {})
            writer.writerow([
                s.get("start_time", ""),
                s.get("end_time", ""),
                task.get("title", ""),
                task.get("estimated_minutes", 0),
                task.get("priority", "medium"),
                task.get("energy_level", "medium"),
                "Yes" if task.get("is_completed") or s.get("status") == "completed" else "No"
            ])

        return output.getvalue()

    @staticmethod
    def export_plan_json(plan_data: Dict[str, Any]) -> str:
        """
        Converts a Daily Plan dictionary into formatted JSON.
        """
        return json.dumps(plan_data, indent=2, default=str)
